#!/bin/sh
set -e

PKG=turtlebot-env-indigo

#DEBHELPER#

case "$1" in
  configure)

    if [ -e /etc/init.d/ps3joy ]; then
      update-rc.d -f ps3joy remove
      update-rc.d ps3joy start 26 2 3 4 5 . stop 74 0 1 6 .
      invoke-rc.d ps3joy restart || true
    fi

    /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas

    # all new users source ros on startup
    #grep '. /etc/ros/setup.bash' /etc/skel/.bashrc >/dev/null 2>&1 || echo ". /etc/ros/setup.bash" >> /etc/skel/.bashrc
    /etc/init.d/avahi-daemon start

    ;;

  *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
