#!/bin/sh

if [ "$1" = remove ]; then
    rm /etc/default/avahi-daemon
    dpkg-divert --package turtlebot-env-indigo --remove --rename \
        --divert /etc/default/avahi-daemon.real /etc/default/avahi-daemon
fi

#DEBHELPER#
